version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 16
    commands:
      - echo CODEBUILD_START_TIME $CODEBUILD_START_TIME
      - npm install -g npm@latest
      - npm --version
      - node --version
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - echo Building demo app
      - npm run build demo-app

artifacts:
  files:
    - "**/*"
  name: viz-library-$CODEBUILD_BUILD_NUMBER-$(date +%Y-%m-%d)-$CODEBUILD_START_TIME
  files: 
    - 'dist/viz-components/**/*'
    - '_deploy_buildspec.yml'
  discard-paths: no
