version: 0.2

phases: 
  install: 
    commands: 
      - echo $CODEBUILD_START_TIME
      - echo $ENVTYPE
      - aws --version
      - echo "Installing Severless Framework for deployment"
      - export SLS_DEBUG=*
      - npm ci
  build:
    on-failure: ABORT 
    commands: 
      - echo serverless deployment 
      - pwd 
      - printenv
      - ls 
      - cd infrastructure
      - npx serverless deploy --verbose --stage $ENVTYPE
      - cd ../${CODEBUILD_SRC_DIR_build_artifacts}
      - unzip frontend.zip -d ./frontend
      - aws s3 rm s3://$S3WebsiteDeployBucket --recursive
      - aws s3 cp ./frontend/dist/demo-app s3://$S3WebsiteDeployBucket --recursive
      - aws s3 cp ./frontend/dist/demo-app/index.html s3://$S3WebsiteDeployBucket/index.html --metadata-directive REPLACE --cache-control no-cache --content-type "text/html"
      - aws cloudfront create-invalidation --distribution-id=$CloudFrontDistributionId --paths "/*"
      - echo front-end deployment complete
