version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g npm@latest
      - npm ci
  build:
    commands:
      - echo building library
      - npm run build viz-components
      - echo building custom schematics
      - npm run build --prefix projects/viz-components
      - echo building code snippets
      - cd projects/viz-components/code-snippets
      - python code_snippet_generator.py
      - cd ../../..
      - cp .vscode/vizcolib-configs.code-snippets dist/viz-components
  post_build:
    commands:
      - echo Zipping package files together
      - zip -r package.zip dist/viz-components

artifacts:
  name: viz-library-$CODEBUILD_BUILD_NUMBER-$(date +%Y-%m-%d)-$CODEBUILD_START_TIME
  files:
    - 'package.zip'
