version: 0.2 

phases: 
  install: 
    commands: 
      - echo $CODEBUILD_START_TIME
      - echo $ENVTYPE
      - aws --version
      - echo "Installing Severless Framework for deployment"
      - export SLS_DEBUG=*
      - npm ci

  pre_build: 
    commands: 
      - echo setting up npm with codeartifact
      - aws codeartifact login --tool npm --repository shared-package-repository --domain shared-package-domain --namespace @web-ast

  build: 
    on-failure: ABORT
    commands:
      - echo publishing
      - cd ${CODEBUILD_SRC_DIR_build_artifacts}
      - unzip package.zip -d ./package 
      - cd package/dist/viz-components
      - npm publish
      - echo Package Release Succeeded!
      - echo serverless deployment 
      - cd ${CODEBUILD_SRC_DIR}
      - pwd 
      - ls 
      - cd infrastructure
      - npx serverless deploy --verbose --stage $ENVTYPE
      - cd ${CODEBUILD_SRC_DIR_build_artifacts}
      - unzip frontend.zip -d ./frontend
      - aws s3 rm s3://$S3WebsiteDeployBucket --recursive
      - aws s3 cp ./frontend/dist/demo-app s3://$S3WebsiteDeployBucket --recursive
      - aws s3 cp ./frontend/dist/demo-app/index.html s3://$S3WebsiteDeployBucket/index.html --metadata-directive REPLACE --cache-control no-cache --content-type "text/html"
      - aws cloudfront create-invalidation --distribution-id=$CloudFrontDistributionId --paths "/*"
      - echo front-end deployment complete