name: Documentation
description: Suggest an improvement to our documentation at material.angular.io
title: 'docs-bug([LIB]-[ITEM]): TITLE'
labels: ['issue type: documentation request', 'triage']
body:
  - type: textarea
    id: description
    attributes:
      label: Documentation Feedback
      description: |
        Provide a brief summary of what you would like to see changed in our documentation at [frontend.shared-packages.mathematica-dev.net](https://frontend.shared-packages.mathematica-dev.net/).
        Feel free to provide any suggestions of content or examples you’d like us to include.
    validations:
      required: true
  - type: input
    id: affected-documentation-page
    attributes:
      label: Affected documentation page
      description: Insert a link to the affected page on [frontend.shared-packages.mathematica-dev.net](https://frontend.shared-packages.mathematica-dev.net/).
    validations:
      required: false
