AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates a codeartifact repository

Parameters:
  AppName:
    Type: String
  RepositoryName:
    Type: String

Resources:
  CodeArtifactDomain:
    Type: AWS::CodeArtifact::Domain
    Properties:
      DomainName: !Sub "${AppName}-library"

  CodeArtifactRepository:
    Type: AWS::CodeArtifact::Repository
    Properties:
      RepositoryName: !Ref RepoName
      DomainName: !GetAtt CodeArtifactDomain.Name
