AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates a domain with an external connection to a package manager's public library. There 
  should only be one of external connection codeartifact repo per domain, and all other 
  codeartifact repositories within the domain should point to this repo as an upstream 
  repo (whether directly or indirectly). 
  See: https://docs.aws.amazon.com/codeartifact/latest/ug/external-connection.html

Parameters:
  DomainName:
    Type: String
  ExternalConnectionSource:
    Type: String
    AllowedValues: ["public:npmjs", "public:pypi", "public:nuget-org"]
  StoreRepositoryName:
    Type: String
    AllowedValues: ["npm", "python", "nuget"]

Resources:
  # By default, packages are private to an account, so no need to create a policy
  # (unless we want other accounts to be able to access this repository)
  StoreRepositoryDomain:
    Type: AWS::CodeArtifact::Domain
    Properties:
      DomainName: !Ref DomainName

  StoreRepository:
    Type: AWS::CodeArtifact::Repository
    Properties:
      Description: !Sub "Store repo for ${StoreRepositoryName}"
      DomainName: !GetAtt StoreRepositoryDomain.Name
      ExternalConnections:
        - !Ref ExternalConnectionSource
      RepositoryName: !Sub "${StoreRepositoryName}-store"

Outputs:
  SourceRepositoryName:
    Value: !GetAtt StoreRepository.Name
