version: 0.2
env:
  exported-variables:
    - BackEndDeployedSourceVersion

phases:
  install:
    commands:
      - echo $CODEBUILD_START_TIME
      - echo $ENVTYPE
      - aws --version
      - echo "Installing Severless Framework for deployment"
      - export SLS_DEBUG=*
      - npm ci

  pre_build:
    commands:
      - |
        if ! [ -f ./frontend.zip ]; then
          export frontendLastBuildId=`aws codebuild list-builds-for-project --project-name ${FrontEndBuildName} | jq -r '.ids[0]'`
          echo frontendLastBuildId $frontendLastBuildId
          export frontendLastBuildArtifactsArn=`aws codebuild  batch-get-builds --ids ${frontendLastBuildId} | jq -r '.builds[0].artifacts.location'`
          echo frontendLastBuildArtifactsArn $frontendLastBuildArtifactsArn
          export frontEndParamValue=s3://${frontendLastBuildArtifactsArn/arn:aws:s3:::} #remove arn prefix
          echo frontEndParamValue $frontEndParamValue
          aws s3 cp ${frontEndParamValue} ./frontend.zip
        fi
  build:
    on-failure: ABORT
    commands:
      - echo "Starting Deploy Process"
      - pwd
      - ls 
      - cd infrastructure
      - ls 
      - npx serverless deploy --verbose --stage $ENVTYPE
      - aws s3 rm s3://$S3WebsiteDeployBucket --recursive
      - aws s3 cp ../dist/demo-app s3://$S3WebsiteDeployBucket --recursive
      - aws s3 cp ../dist/demo-app/index.html s3://$S3WebsiteDeployBucket/index.html --metadata-directive REPLACE --cache-control no-cache --content-type "text/html"
      - aws cloudfront create-invalidation --distribution-id=$CloudFrontDistributionId --paths "/*"

  post_build:
    commands:
      - echo '$CODEBUILD_BUILD_SUCCEEDING' $CODEBUILD_BUILD_SUCCEEDING
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi" #Don't write to parameter store if its not successful!
      - echo "Front end Deployment Complete!"
      - echo "Parameter Name" $DeployedSourceVersionParameter
      - echo "CODEBUILD_SOURCE_VERSION" $CODEBUILD_SOURCE_VERSION
      - aws ssm put-parameter --name $DeployedSourceVersionParameter --value $CODEBUILD_SOURCE_VERSION --type String --overwrite
      - BackEndDeployedSourceVersion=$CODEBUILD_SOURCE_VERSION

artifacts:
  files:
    - "infrastructure/archive-assets.yml"
    - "infrastructure/deploy_buildspec.yml"
    - "deploy-package.zip"
    - "package-lock.json"
    - "package.json"
    - "infrastructure/serverless.yml"
    - "infrastructure/serverless-config.yml"
    - "frontend.zip"
  discard-paths: no
