AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloudformation for CI pipeline in AWS using Codepipeline and Code Build for viz components library

Parameters:
  AppName: 
    Type: String
  BranchName:
    Description: GitHub branch name
    Type: String
    Default: VIZCOLIB-87-package-codepipeline
  GithubOwner:
    Type: String
  RepositoryName:
    Type: String
  GithubSecret:
    Type: String
  ArtifactBucketName:
    Type: String
    Default: ""
  TestAndBuildSpecLocation: 
    Type: String 
    Default: buildspecs/package_build.yml
  ReleaseSpecLocation:
    Type: String 
    Default: buildspecs/package_release.yml

Conditions: 
  NoArtifactBucketNameProvided: !Equals [!Ref ArtifactBucketName, ""]

Resources:
  GetPutArtifactBucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Resource: !Sub 
            - '${ArtifactArn}/*'
            - ArtifactArn: !GetAtt ArtifactBucket.Arn
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
      PolicyName: GetPutSourceBucket
      Roles:
        - !Ref CodeBuildRole
        - !Ref CodePipelineRole

  ListBucketsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Resource: '*'
          Action: 
            - 's3:ListAllMyBuckets'
            - 's3:ListStorageLensConfigurations'
      PolicyName: ListBuckets
      Roles:
        - !Ref CodeBuildRole
        - !Ref CodePipelineRole

  WriteToCodeArtifactRepositoryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: 
              - arn:aws:codeartifact:us-east-1:922539530544:domain/shared-package-domain
            Action: 
              - "codeartifact:DescribeDomain"
              - "codeartifact:DescribePackageVersion"
              - "codeartifact:GetAuthorizationToken"
              - "codeartifact:GetDomainPermissionsPolicy"
              - "codeartifact:ListRepositoriesInDomain"
          - Effect: Allow
            Resource: 
              - arn:aws:codeartifact:us-east-1:922539530544:repository/shared-package-domain/shared-package-repository
            Action: 
              - "codeartifact:DescribeRepository"
              - "codeartifact:GetPackageVersionAsset"
              - "codeartifact:GetPackageVersionReadme"
              - "codeartifact:GetRepositoryEndpoint"
              - "codeartifact:GetRepositoryPermissionsPolicy"
              - "codeartifact:ListPackageVersionAssets"
              - "codeartifact:ListPackageVersionDependencies"
              - "codeartifact:ListPackageVersions"
              - "codeartifact:ListPackages"
              - "codeartifact:ListTagsForResource"
              - "codeartifact:PutPackageMetadata"
              - "codeartifact:ReadFromRepository"
              - "codeartifact:TagResource"
              - "codeartifact:UntagResource"
          - Effect: Allow 
            Resource: 
              - arn:aws:codeartifact:us-east-1:922539530544:package/shared-package-domain/shared-package-repository/*/*/*
            Action: 
              - "codeartifact:PublishPackageVersion"

      PolicyName: WriteToRepository
      Roles:
        - !Ref CodeBuildRole

  LogStreamsPolicy: 
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Resource: '*'
          Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:GetLogEvents'
            - 'logs:PutLogEvents'
      PolicyName: LogStreams
      Roles:
        - !Ref CodeBuildRole

  StartCodeBuildPolicy: 
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement: 
          Effect: Allow
          Resource: 
            - !Sub 
              - arn:aws:codebuild:${Region}:${AccountId}:project/${CodeBuild}
              - Region: !Ref 'AWS::Region'
                AccountId: !Ref 'AWS::AccountId'
                CodeBuild: !Ref TestAndBuild
            - !Sub 
              - arn:aws:codebuild:${Region}:${AccountId}:project/${CodeBuild}
              - Region: !Ref 'AWS::Region'
                AccountId: !Ref 'AWS::AccountId'
                CodeBuild: !Ref Release
          Action:
            - 'codebuild:StartBuild'
            - 'codebuild:BatchGetBuilds' 
      PolicyName: StartCodeBuild
      Roles: 
        - !Ref CodePipelineRole

  UseBearerTokenPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Resource: '*'
          Action: 
            - "sts:GetServiceBearerToken"
      PolicyName: UseBearerToken
      Roles:
        - !Ref CodeBuildRole

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/Math-Boundary-Policy
      RoleName: !Join ["-", [ "MathRole", "CodeBuild", !Ref AppName ] ]

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/Math-Boundary-Policy
      RoleName: !Join ["-", [ "MathRole", "CodePipeline", !Ref AppName ] ]

  ArtifactBucket: 
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !If [NoArtifactBucketNameProvided, !Join ["-", [!Ref AppName, "artifact-bucket"]], 
        !Ref ArtifactBucketName]
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Delete 

  TestAndBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
      Artifacts:
        Type: CODEPIPELINE
      Description: !Join [" ", ["code build and test for ", !Ref AppName] ] 
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
      Name: !Join ["-", ["test-and-build", !Ref AppName ] ]
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref TestAndBuildSpecLocation
  
  Release: 
    Type: AWS::CodeBuild::Project 
    Properties:
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
      Artifacts:
        Type: CODEPIPELINE 
      Description: !Join [" ", ["package release for ", !Ref AppName] ] 
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
      Name: !Join ["-", ["codebuild-release", !Ref AppName ] ]
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref ReleaseSpecLocation 
   
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !If [NoArtifactBucketNameProvided, !Join ["-", [!Ref AppName, "artifact-bucket"]], 
          !Ref ArtifactBucketName]
      Name: !Join ["-", [ "pipeline", !Ref AppName] ]
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              Configuration:
                Owner: !Ref GithubOwner
                Repo: !Ref RepositoryName
                Branch: !Ref BranchName
                OAuthToken: !Sub '{{resolve:secretsmanager:${GithubSecret}:SecretString:token}}'
                PollForSourceChanges: false
              Name: !Join ["-", ["source", "repo", !Ref AppName] ] 
              OutputArtifacts:
                - Name: !Sub "source-repo-artifacts-${AppName}"
              RunOrder: 1
        - Name: TestAndBuild
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref TestAndBuild
              InputArtifacts:
                - Name: !Sub "source-repo-artifacts-${AppName}"
              Name:  !Join ["-", [ "build", !Ref AppName ] ]
              OutputArtifacts:
                - Name:  !Sub "test-and-build-artifacts-${AppName}"
              RunOrder: 1
        - Name: Release
          Actions:
            - Name: Approval_to_publish
              RunOrder: 1 
              InputArtifacts: []
              OutputArtifacts: []
              ActionTypeId: 
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual 
              
            - Name: Publish 
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref Release
              InputArtifacts:
                - Name: !Sub "test-and-build-artifacts-${AppName}"
              OutputArtifacts:
                - Name:   !Sub "release-artifacts-${AppName}"
              RunOrder: 2

  AppPipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Sub '{{resolve:secretsmanager:${GithubSecret}:SecretString:token}}'
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
      TargetPipeline: !Ref CodePipeline
      TargetAction: !Join ["-", ["source", "repo", !Ref AppName] ] 
      Name: !Join ["-",  [AppPipelineWebhook, !Ref AppName]]
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true
