AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloudformation for CI pipeline in AWS using Codepipeline and Code Build for viz components library

Parameters:
  AppName: 
    Type: String
  BranchName:
    Description: GitHub branch name
    Type: String
    Default: VIZCOLIB-86-website-in-package-pipeline
  GithubOwner:
    Type: String
  RepositoryName:
    Type: String
  GithubSecret:
    Type: String
  ArtifactBucketName:
    Type: String
    Default: ""
  LintSpecLocation: 
    Type: String 
    Default: buildspecs/package-lint.yml
  TestSpecLocation: 
    Type: String 
    Default: buildspecs/package-test.yml
  PackageBuildSpecLocation: 
    Type: String 
    Default: buildspecs/package-build.yml
  ReleaseSpecLocation:
    Type: String 
    Default: buildspecs/package-release.yml
  DevDeploySpecLocation:
    Type: String
    Default: buildspecs/dev-deploy.yml

Conditions: 
  NoArtifactBucketNameProvided: !Equals [!Ref ArtifactBucketName, ""]

Resources:
  GetPutArtifactBucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Resource: !Sub 
            - '${ArtifactArn}/*'
            - ArtifactArn: !GetAtt ArtifactBucket.Arn
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
      PolicyName: GetPutSourceBucket
      Roles:
        - !Ref CodeBuildRole
        - !Ref CodePipelineRole

  ListBucketsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Resource: '*'
          Action: 
            - 's3:ListAllMyBuckets'
            - 's3:ListStorageLensConfigurations'
      PolicyName: ListBuckets
      Roles:
        - !Ref CodeBuildRole
        - !Ref CodePipelineRole

  ServerlessAgentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'MathPolicy-ServerlessAgent-${AppName}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
            - secretsmanager:*
            - apigateway:*
            - lambda:*
            - s3:*
            - s3:PutBucketAcl
            - ec2:*
            - ssm:*
            - cloudfront:*
            - cloudformation:CancelUpdateStack
            - cloudformation:ContinueUpdateRollback
            - cloudformation:CreateChangeSet
            - cloudformation:CreateStack
            - cloudformation:CreateUploadBucket
            - cloudformation:DeleteStack
            - cloudformation:DeleteChangeSet
            - cloudformation:Describe*
            - cloudformation:EstimateTemplateCost
            - cloudformation:ExecuteChangeSet
            - cloudformation:Get*
            - cloudformation:List*
            - cloudformation:PreviewStackUpdate
            - cloudformation:UpdateStack
            - cloudformation:UpdateTerminationProtection
            - cloudformation:ValidateTemplate
            - events:DeleteRule
            - events:DescribeRule
            - events:ListRuleNamesByTarget
            - events:ListRules
            - events:ListTargetsByRule
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - iam:CreateServiceLinkedRole
            - iam:CreateRole
            - iam:DeleteRole
            - iam:DeleteRolePolicy
            - iam:GetRole
            - iam:GetRolePolicy
            - iam:PassRole
            - iam:PutRolePolicy
            - iam:AttachRolePolicy
            - iam:DetachRolePolicy
            - iam:UpdateAssumeRolePolicy
            - iam:UpdateAssumeRolePolicyDocument
            - iam:ListAttachedRolePolicies
            - iam:DeleteRole
            - logs:CreateLogGroup
            - logs:DeleteLogGroup
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:FilterLogEvents
            - logs:GetLogEvents
            - sns:CreateTopic
            - sns:DeleteTopic
            - sns:GetSubscriptionAttributes
            - sns:GetTopicAttributes
            - sns:ListSubscriptions
            - sns:ListSubscriptionsByTopic
            - sns:ListTopics
            - sns:SetSubscriptionAttributes
            - sns:SetTopicAttributes
            - sns:Subscribe
            - sns:Unsubscribe
            - sns:TagResource
          Resource: '*'
      Roles:
        - !Ref CodeBuildRole

  WriteToCodeArtifactRepositoryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: 
              - arn:aws:codeartifact:us-east-1:922539530544:domain/shared-package-domain
            Action: 
              - "codeartifact:DescribeDomain"
              - "codeartifact:DescribePackageVersion"
              - "codeartifact:GetAuthorizationToken"
              - "codeartifact:GetDomainPermissionsPolicy"
              - "codeartifact:ListRepositoriesInDomain"
          - Effect: Allow
            Resource: 
              - arn:aws:codeartifact:us-east-1:922539530544:repository/shared-package-domain/shared-package-repository
            Action: 
              - "codeartifact:DescribeRepository"
              - "codeartifact:GetPackageVersionAsset"
              - "codeartifact:GetPackageVersionReadme"
              - "codeartifact:GetRepositoryEndpoint"
              - "codeartifact:GetRepositoryPermissionsPolicy"
              - "codeartifact:ListPackageVersionAssets"
              - "codeartifact:ListPackageVersionDependencies"
              - "codeartifact:ListPackageVersions"
              - "codeartifact:ListPackages"
              - "codeartifact:ListTagsForResource"
              - "codeartifact:PutPackageMetadata"
              - "codeartifact:ReadFromRepository"
              - "codeartifact:TagResource"
              - "codeartifact:UntagResource"
          - Effect: Allow 
            Resource: 
              - arn:aws:codeartifact:us-east-1:922539530544:package/shared-package-domain/shared-package-repository/*/*/*
            Action: 
              - "codeartifact:PublishPackageVersion"

      PolicyName: WriteToRepository
      Roles:
        - !Ref CodeBuildRole

  LogStreamsPolicy: 
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Resource: '*'
          Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:GetLogEvents'
            - 'logs:PutLogEvents'
      PolicyName: LogStreams
      Roles:
        - !Ref CodeBuildRole

  StartCodeBuildPolicy: 
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement: 
          Effect: Allow
          Resource: 
           - !GetAtt CodeBuildLint.Arn
           - !GetAtt CodeBuildPackage.Arn
           - !GetAtt CodeBuildRelease.Arn
           - !GetAtt CodeBuildTest.Arn
           - !GetAtt CodeBuildDevDeploy.Arn
          Action:
            - 'codebuild:StartBuild'
            - 'codebuild:BatchGetBuilds' 
      PolicyName: StartCodeBuild
      Roles: 
        - !Ref CodePipelineRole

  UseBearerTokenPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Resource: '*'
          Action: 
            - "sts:GetServiceBearerToken"
      PolicyName: UseBearerToken
      Roles:
        - !Ref CodeBuildRole

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/Math-Boundary-Policy
      RoleName: !Join ["-", [ "MathRole", "CodeBuild", !Ref AppName ] ]

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/Math-Boundary-Policy
      RoleName: !Join ["-", [ "MathRole", "CodePipeline", !Ref AppName ] ]

  ArtifactBucket: 
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !If [NoArtifactBucketNameProvided, 
        !Join ["-", [!Ref AppName, "artifact-bucket"]], 
        !Ref ArtifactBucketName]
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Delete 

  CodeBuildLint:
    Type: AWS::CodeBuild::Project
    Properties:
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub "lint for ${AppName}"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
      Name: !Sub "lint-${AppName}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref LintSpecLocation
  
  CodeBuildDevDeploy:
    Type: AWS::CodeBuild::Project
    Properties:
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub "dev deploy for ${AppName}"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
        EnvironmentVariables:
          - Name: ENVTYPE
            Type: PLAINTEXT
            Value: dev
          - Name: S3WebsiteDeployBucket
            Type: PLAINTEXT
            Value: viz-components-demo-app-dev-frontend-app
          - Name: CloudFrontDistributionId
            Type: PLAINTEXT
            Value: ESAQGKQBO7BYX
      Name: !Sub "dev-deploy-${AppName}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref DevDeploySpecLocation
        
  CodeBuildTest:
    Type: AWS::CodeBuild::Project
    Properties:
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub "test for ${AppName}"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
      Name: !Sub "test-${AppName}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref TestSpecLocation

  CodeBuildPackage:
    Type: AWS::CodeBuild::Project
    Properties:
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub "package build for ${AppName}"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
      Name: !Sub "package-build-${AppName}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref PackageBuildSpecLocation
  
  CodeBuildRelease: 
    Type: AWS::CodeBuild::Project 
    Properties:
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
      Artifacts:
        Type: CODEPIPELINE 
      Description: !Sub "package release for ${AppName}"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
        EnvironmentVariables:
          - Name: ENVTYPE
            Type: PLAINTEXT
            Value: release
          - Name: S3WebsiteDeployBucket
            Type: PLAINTEXT
            Value: viz-components-demo-app-release-frontend-app
          - Name: CloudFrontDistributionId
            Type: PLAINTEXT
            Value: E1AON68T11GML9
      Name: !Sub "codebuild-release-${AppName}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref ReleaseSpecLocation 
   
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !If [NoArtifactBucketNameProvided, !Join ["-", [!Ref AppName, "artifact-bucket"]], 
          !Ref ArtifactBucketName]
      Name: !Join ["-", [ "pipeline", !Ref AppName] ]
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              Configuration:
                Owner: !Ref GithubOwner
                Repo: !Ref RepositoryName
                Branch: !Ref BranchName
                OAuthToken: !Sub '{{resolve:secretsmanager:${GithubSecret}:SecretString:token}}'
                PollForSourceChanges: false
              Name: !Sub "source-repo-${AppName}" 
              OutputArtifacts:
                - Name: !Sub "source_repo_artifacts_${AppName}"
              RunOrder: 1
        - Name: Build
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildLint
              InputArtifacts:
                - Name: !Sub "source_repo_artifacts_${AppName}"
              Name:  !Sub "lint-${AppName}"
              OutputArtifacts:
                - Name:  "lint_artifacts"
              RunOrder: 1
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildTest
              InputArtifacts:
                - Name: !Sub "source_repo_artifacts_${AppName}"
              Name:  !Sub "test-${AppName}"
              OutputArtifacts:
                - Name:  "test_artifacts"
              RunOrder: 1 
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildPackage
              InputArtifacts:
                - Name: !Sub "source_repo_artifacts_${AppName}"
              Name:  !Sub "build-${AppName}"
              OutputArtifacts:
                - Name:  "build_artifacts"
              RunOrder: 1 
        - Name: DevDeploy
          Actions: 
            - Name: DevDeploy
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration: 
                ProjectName: !Ref CodeBuildDevDeploy
                PrimarySource: !Sub "source_repo_artifacts_${AppName}"
              InputArtifacts: 
                - Name: !Sub "source_repo_artifacts_${AppName}"
                - Name: "build_artifacts"
              OutputArtifacts: 
                - Name: dev_deploy_artifacts
              RunOrder: 1
        - Name: Release
          Actions:
            - Name: Publish 
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildRelease
                PrimarySource: !Sub "source_repo_artifacts_${AppName}"
              InputArtifacts:
                - Name: !Sub "source_repo_artifacts_${AppName}"
                - Name: "build_artifacts"
              OutputArtifacts:
                - Name: "release_artifacts"
              RunOrder: 1

  AppPipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Sub '{{resolve:secretsmanager:${GithubSecret}:SecretString:token}}'
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
      TargetPipeline: !Ref CodePipeline
      TargetAction: !Join ["-", ["source", "repo", !Ref AppName] ] 
      Name: !Join ["-",  [AppPipelineWebhook, !Ref AppName]]
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true
