Parameters:
  VariableName: This is a variable
Resources:
  Thing1: !Sub "hello ${variableName}"
  Thing2: This is a string name
  Thing3:
    Thing4:
    - This is a nested string
    - This is a string name
    TestOverrideMe: test this
  Thing5:
    Thing4:
    - This is a nested string
    - This is a string name
    TestOverrideMe: test this
  # overridden version
  Thing6:
    Thing4:
    - This is a nested string
    - This is a string name
    TestOverrideMe: test this
